###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

#This is a comment. Comments are ignored by Docker Compose.

version: '3.1'
#This line specifies the version of Docker Compose that the file is compatible with.

services:
#This section defines the services that will be created and managed by Docker Compose.

    mailhog:
      # image: 'mailhog/mailhog:latest' original
        image: 'cd2team/mailhog:latest' # replacement test for arm
        ports:
            - '17000:8025'
    #This service defines a mailhog container. The image property specifies the Docker image to use for the container. The ports property maps the container's port 8025 to the host's port 17000.

    redis:
        image: 'redis:alpine'
    #This service defines a redis container.


    # mariadb:
        # image: 'mariadb:11.0'
        # working_dir: /application
        # volumes:
            # - '.:/application'
        # environment:
            # - MYSQL_ROOT_PASSWORD=12345
            # - MYSQL_DATABASE=app
            # - MYSQL_USER=user
            # - MYSQL_PASSWORD=apppass
        # ports:
            # - '17002:3306'
    # This service defines a mariadb container. 
    # The working_dir property specifies the working directory for the container. 
    # The volumes property mounts the current directory on the host to the /application directory in the container. 
    # The environment property sets environment variables for the container. The ports property maps the container's port 3306 to the host's port 17002.

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
             - ./app:/application
             - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '16999:80'
    # This service defines a nginx container. 
    # The volumes property mounts a directory on the host named app to the /application directory in the container. 
    # The volumes property also mounts the ./phpdocker/nginx/nginx.conf file on the host to the /etc/nginx/conf.d/default.conf file in the container. The ports property maps the container's port 80 to the host's port 16999.


    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
        # command: ["composer", "install", "--no-interaction", "--ignore-platform-reqs"]
    
    #This service defines a php-fpm container. The build property specifies the Dockerfile to use to build the container. 
    #The working_dir property specifies the working directory for the container. The volumes property mounts the current directory on the host to the /application directory in the container. 
    # The volumes property also mounts the ./phpdocker/php-fpm/php-ini-overrides.ini file on the host to the /etc/php/7.4/fpm/conf.d/99-overrides.ini file in the container.
    # docker-compose.yml file will create a complete development environment for a PHP application. The mailhog container will be used to send and receive emails. The redis container will be used as a cache. The mariadb container will be used as a database. The nginx container will be used as a web server. The php-fpm container will be used to run the PHP application.
